Fix security analysis references.
mlswg/mls-architecture pull request #119
Opened 2022-08-23 05:30 UTC by rohan-wire

The references at the end of the Security Considerations weren't in kramdown format. Fixed.

2022-12-14 14:39 UTC, mulmarta requested changes

2022-12-14 14:39 UTC, mulmarta commented on draft-ietf-mls-architecture.md
> +      - name: Yiannis Tselekounis
Please swap Yiannis Tselekounis => Marta Mularczyk

2022-12-14 15:30 UTC, beurdouche approved these changes

2022-12-14 15:30 UTC, beurdouche commented on draft-ietf-mls-architecture.md
> +      - name: Yiannis Tselekounis
```suggestion
      - name: Marta Mularczyk
```

2022-12-15 19:30 UTC, bifurcation commented on draft-ietf-mls-architecture.md
> -
This section isn't needed; references will be auto-generated from the YAML.

2022-12-15 20:06 UTC, bifurcation commented on draft-ietf-mls-architecture.md
> -
Oops, never mind, I missed that this section is deleted, not added.

2022-12-15 20:15 UTC, bifurcation commented on draft-ietf-mls-architecture.md
> +
```suggestion

```

2022-12-15 20:17 UTC, merged