Remove recommendation not to have the AS generated keys
mlswg/mls-architecture pull request #224
Opened 2023-11-07 19:24 UTC by ekr

This removes the text suggesting that the AS not generate keys. I agree that this is the best practice, but it's just such a standard practice that i think even mentioning the alternative creates confusion.

2023-11-08 08:06 UTC, beurdouche requested changes
I don't think this should be removed. To my knowledge, there are enough non-PKI driven use cases to justify this graph. 

Maybe we can attenuate the language to make this "acceptable" ?

2023-11-08 08:33 UTC, ekr commented
In what use cases does the AS generate the key pairs?

2023-11-10 10:22 UTC, rohan-wire commented
Maybe we could just strengthen the text to say basically:

"Some service did this in the past. DON'T DO THIS!!!! (really!)"

2023-11-11 08:49 UTC, ekr commented
See above.

2023-11-12 12:43 UTC, rohan-wire approved these changes

2024-01-19 13:42 UTC, beurdouche commented
I misread Ekr's comment in my first review. We actually all agree.

2024-01-19 13:42 UTC, merged